//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvariCapitalCRM.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorMediaFile
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int MediaType { get; set; }
        public string NewFileName { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<long> MediaSize { get; set; }
        public int MediaSort { get; set; }
        public string MediaCloudId { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
