//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvariCapitalCRM.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadLog
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public long MaterialId { get; set; }
        public long MediaFileId { get; set; }
        public string MediaFileName { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
