//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvariCapitalCRM.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContextEntities : DbContext
    {
        public DataContextEntities()
            : base("name=DataContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMSMessageLog> SMSMessageLogs { get; set; }
        public virtual DbSet<TestUser> TestUsers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<DownloadLog> DownloadLogs { get; set; }
        public virtual DbSet<DistributorMediaFile> DistributorMediaFiles { get; set; }
        public virtual DbSet<MediaFile> MediaFiles { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
    }
}
